name: CI - Build, Test and Push FastAPI to ECR

on:
  push:
    branches:
      - frontend
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- Install Python ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ---------- Install Dependencies ----------
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      # ---------- Run Tests ----------
      - name: Run tests
        run: |
          cd backend
          pytest

      # ---------- Configure AWS ----------
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v2

      # ---------- Build & Push Docker ----------
      - name: Build, Tag, Push
        env:
          ECR_REGISTRY: 264119764851.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: fastapi-backend
        run: |
          docker build -t $ECR_REPOSITORY ./backend
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # ---------- Trigger CodeDeploy ----------
      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name fastapi-app \
            --deployment-group-name fastapi-deployment-group \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
